<script setup>
import { ref, computed } from 'vue';

const accountingReport = ref([
  {
    title: 'Balance Sheet',
    description: 'Shows the overall financial health of your business.',
    items: [
      {
        title: 'Liabilities',
        description: 'The debts and obligations of your business.',
        value: 1000000,
      },
      {
        title: 'Equities',
        description: 'The ownership interest in your business.',
        value: 2000000,
      },
      {
        title: 'Assets',
        description: 'The resources owned by your business.',
        value: 3000000,
      },
    ],
  },
  {
    title: 'Income Statement',
    description: 'Shows the profitability of your business.',
    items: [
      {
        title: 'Revenue',
        description: 'The income generated by your business.',
        value: 5000000,
      },
      {
        title: 'Expenses',
        description: 'The costs incurred by your business.',
        value: 3500000,
      },
      {
        title: 'Net Income',
        description: 'The profit or loss of your business.',
        value: 1500000,
      },
    ],
  },
  {
    title: 'Cash Flow Statement',
    description: 'Shows the cash inflows and outflows for your business.',
    items: [
      {
        title: 'Net Cash from Operations',
        description: 'The cash generated by your business operations.',
        value: 1200000,
      },
      {
        title: 'Net Cash from Investing',
        description: 'The cash used for or generated by your business investments.',
        value: -500000,
      },
      {
        title: 'Net Cash from Financing',
        description: 'The cash used for or generated by your business financing.',
        value: 800000,
      },
      {
        title: 'Ending Cash Balance',
        description: 'The cash balance at the end of the period.',
        value: 1500000,
      },
    ],
  },
]);

const grade = ref(4.5);

const fullStars = computed(() => Math.floor(grade.value));
const hasHalfStar = computed(() => grade.value % 1 !== 0);
const emptyStars = computed(() => 5 - Math.ceil(grade.value));
</script>

<template>
    <div class="accounting-report">
      <h1>Accounting Report</h1>
  
      <div class="grade-container">
        <div class="grade-stars">
          <svg v-for="n in fullStars" :key="n" xmlns="http://www.w3.org/2000/svg" width="1.2em" height="1.2em" viewBox="0 0 24 24">
            <path fill="white" d="m12 18.275l-4.15 2.5q-.275.175-.575.15t-.525-.2q-.225-.175-.35-.437t-.05-.588l1.1-4.725L3.775 11.8q-.25-.225-.312-.513t.037-.562q.1-.275.3-.45t.55-.225l4.85-.425l1.875-4.45q.125-.3.388-.45t.537-.15q.275 0 .537.15t.388.45l1.875 4.45l4.85.425q.35.05.55.225t.3.45q.1.275.038.563t-.313.512l-3.675 3.175l1.1 4.725q.075.325-.05.588t-.35.437q-.225.175-.525.2t-.575-.15z"/>
          </svg>
          <svg v-if="hasHalfStar" xmlns="http://www.w3.org/2000/svg" width="1.2em" height="1.2em" viewBox="0 0 24 24">
          <path fill="white" d="M12 17.275l-4.15 2.5q-.275.175-.575.15t-.525-.2q-.225-.175-.35-.437t-.05-.588l1.1-4.725L3.775 10.8q-.25-.225-.312-.513t.037-.562q.1-.275.3-.45t.55-.225l4.85-.425l1.875-4.45q.125-.3.388-.45t.537-.15q.275 0 .537.15t.388.45l1.875 4.45l4.85.425q.35.05.55.225t.3.45q.1.275.038.563t-.313.512l-3.675 3.175l1.1 4.725q.075.325-.05.588t-.35.437q-.225.175-.525.2t-.575-.15z"/>
          <path fill="black" d="M12 17.275l4.15 2.5q.275.175.575.15t.525-.2q.225-.175.35-.437t.05-.588l-1.1-4.725l3.675-3.175q.25-.225.313-.512t-.038-.563q-.1-.275-.3-.45t-.55-.225l-4.85-.425l-1.875-4.45q-.125-.3-.388-.45t-.537-.15z"/>
        </svg>
        <svg v-for="n in emptyStars" :key="n" xmlns="http://www.w3.org/2000/svg" width="1.2em" height="1.2em" viewBox="0 0 24 24">
          <path fill="white" d="m12 18.275l-4.15 2.5q-.275.175-.575.15t-.525-.2q-.225-.175-.35-.437t-.05-.588l1.1-4.725L3.775 11.8q-.25-.225-.312-.513t.037-.562q.1-.275.3-.45t.55-.225l4.85-.425l1.875-4.45q.125-.3.388-.45t.537-.15q.275 0 .537.15t.388.45l1.875 4.45l4.85.425q.35.05.55.225t.3.45q.1.275.038.563t-.313.512l-3.675 3.175l1.1 4.725q.075.325-.05.588t-.35.437q-.225.175-.525.2t-.575-.15z"/>
        </svg>
      </div>
      <span class="grade-value">{{ grade }}/5</span>
    </div>
    <div v-for="(section, index) in accountingReport" :key="index" class="section-container">
      <div class="section-header" @click="section.isOpen = !section.isOpen">
        <h2>{{ section.title }}</h2>
        <span class="toggle-icon">{{ section.isOpen ? '-' : '+' }}</span>
      </div>
      <div v-if="section.isOpen" class="section-content">
        <p>{{ section.description }}</p>
        <div v-for="(item, itemIndex) in section.items" :key="itemIndex" class="item-container">
          <div class="item-header" @click="item.isOpen = !item.isOpen">
            <h3>{{ item.title }}</h3>
            <span class="toggle-icon">{{ item.isOpen ? '-' : '+' }}</span>
          </div>
          <div v-if="item.isOpen" class="item-content">
            <p>{{ item.description }}</p>
            <p>Value: {{ item.value.toLocaleString('en-US', { style: 'currency', currency: 'USD' }) }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.accounting-report {
  font-family: Arial, sans-serif;
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
  background-color: #222;
  color: #fff;
  border-radius: 5px;
  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
}

h1 {
  font-size: 24px;
  margin-bottom: 20px;
  text-align: center;
}

.grade-container {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  margin-bottom: 20px;
}

.grade-stars {
  display: flex;
  align-items: center;
}

.grade-value {
  font-size: 18px;
  margin-left: 10px;
}

.section-container {
  margin-bottom: 20px;
  border: 1px solid #444;
  border-radius: 5px;
  overflow: hidden;
}

.section-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px;
  background-color: #333;
  cursor: pointer;
}

.section-header h2 {
  font-size: 20px;
  margin: 0;
}

.toggle-icon {
  font-size: 18px;
  font-weight: bold;
}

.section-content {
  padding: 10px;
}

.item-container {
  margin-bottom: 10px;
  border: 1px solid #444;
  border-radius: 5px;
  overflow: hidden;
}

.item-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px;
  background-color: #444;
  cursor: pointer;
}

.item-header h3 {
  font-size: 18px;
  margin: 0;
}

.item-content {
  padding: 10px;
}
</style>